### ISSUE TITLE
Effect?

### ISSUE THREAD

**Issue by Patra3** [TonyDroidd/JoinEffect#6]
I believe that Pocketmine doesn't support effects YET. Minecraft PE 0.11 comes out with effects added, but PocketMine at the moment doesn't support effects.
Furthermore, on the docs.pocketmine, it doesn't say anything about effects from entities. Are you sure that you are doing this right?

**Comment by TonyDroidd** [comment]
Pocketmine already supports the defects, and have tried.

**Comment by Patra3** [comment]
KK I'll have to look into that.
