### ISSUE TITLE
One feature 

### ISSUE THREAD

**Issue by ZGamerOficial** [TonyDroidd/JoinEffect#9]
The effect when player join the server.have the effect in every warps.can you add only for lobby?thanks!

**Comment by JoahDave** [comment]
Use a plugin. INVALID

**Comment by TonyDroidd** [comment]
Like Multi-World Effcets?

**Comment by ZGamerOficial** [comment]
Yes!

**Comment by TonyDroidd** [comment]
ok, ill try add for the next update :)

**Comment by ZGamerOficial** [comment]
Awesome!
